# TypeProf 0.21.7

# Classes
class GithubActionsSecretManager
  attr_reader org: untyped
  attr_reader client: untyped
  def initialize: (String org, String token) -> void
  def add_organization_secret_to_selected_repo: (untyped repo_id, untyped secret_name) -> untyped
  def add_organization_secret_to_selected_repos: (untyped repo_ids, untyped secret_name) -> untyped
end
